GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI1ZmQ5MDViMjAxYzE4YzA3NzgxMTU1MGIiLCJpYXQiOjE2MDgwNjUwMjd9.CTMuV4PRfwU1A3-v-7IvcS68RsqySs9rBXC3UZpfHE8

{
    "title": "Teach Yourself node in 3 hr",
    "author": "root 2",
    "url": "asdkj",
    "likes": 13
}

###
DELETE http://localhost:3003/api/blogs/5fd9204f9ca3f92a38386b77
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI1ZmQ5MDViMjAxYzE4YzA3NzgxMTU1MGIiLCJpYXQiOjE2MDgwNjUwMjd9.CTMuV4PRfwU1A3-v-7IvcS68RsqySs9rBXC3UZpfHE8
